config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :chief_editors
  resources :writers
  resources :users
  resources :organizations

  resources :sessions, only: [:new, :create, :destroy]

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  get ':id', to: 'home#index', constraints: { id: /\d+/ }

  get 'stories/new', to: 'stories#new'
  post 'stories/create', to: 'stories#create'
  
  get 'stories/:id/edit', to: 'stories#edit', constraints: { id: /\d+/ }
  post 'stories/:id/update', to: 'stories#update', constraints: { id: /\d+/ }
  post 'stories/:id/status', to: 'stories#status', constraints: { id: /\d+/ }
  post 'stories/:id/comment', to: 'stories#comment', constraints: { id: /\d+/ }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/writer.rb
class Writer < User
  belongs_to :organization
  has_secure_password
end

app/controllers/writers_controller.rb
class WritersController < ApplicationController
  before_action :set_writer, only: [:show, :edit, :update, :destroy]

  # GET /writers
  # GET /writers.json
  def index
    @writers = Writer.all
  end

  # GET /writers/1
  # GET /writers/1.json
  def show
  end

  # GET /writers/new
  def new
    @writer = Writer.new
  end

  # GET /writers/1/edit
  def edit
  end

  # POST /writers
  # POST /writers.json
  def create
    @writer = Writer.new(writer_params)

    respond_to do |format|
      if @writer.save
        format.html { redirect_to @writer, notice: 'Writer was successfully created.' }
        format.json { render :show, status: :created, location: @writer }
      else
        format.html { render :new }
        format.json { render json: @writer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /writers/1
  # PATCH/PUT /writers/1.json
  def update
    respond_to do |format|
      if @writer.update(writer_params)
        format.html { redirect_to @writer, notice: 'Writer was successfully updated.' }
        format.json { render :show, status: :ok, location: @writer }
      else
        format.html { render :edit }
        format.json { render json: @writer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /writers/1
  # DELETE /writers/1.json
  def destroy
    @writer.destroy
    respond_to do |format|
      format.html { redirect_to writers_url, notice: 'Writer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_writer
      @writer = Writer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def writer_params
      params.require(:writer).permit(:name, :email, :password, :password_confirmation, :type, :organization_id)
    end
end

app/helpers/writers_helper.rb
module WritersHelper
end

app/views/writers/_form.html.erb
<%= form_with(model: writer, local: true) do |form| %>
  <% if writer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(writer.errors.count, "error") %> prohibited this writer from being saved:</h2>

      <ul>
        <% writer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :organization_id %>
    <%= form.text_field :organization_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/writers/edit.html.erb
<h1>Editing Writer</h1>

<%= render 'form', writer: @writer %>

<%= link_to 'Show', @writer %> |
<%= link_to 'Back', writers_path %>

app/views/writers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Writers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Type</th>
      <th>Organization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @writers.each do |writer| %>
      <tr>
        <td><%= writer.name %></td>
        <td><%= writer.email %></td>
        <td><%= writer.type %></td>
        <td><%= writer.organization_id %></td>
        <td><%= link_to 'Show', writer %></td>
        <td><%= link_to 'Edit', edit_writer_path(writer) %></td>
        <td><%= link_to 'Destroy', writer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Writer', new_writer_path %>

app/views/writers/new.html.erb
<h1>New Writer</h1>

<%= render 'form', writer: @writer %>

<%= link_to 'Back', writers_path %>

app/views/writers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @writer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @writer.email %>
</p>

<p>
  <strong>Type:</strong>
  <%= @writer.type %>
</p>

<p>
  <strong>Organization:</strong>
  <%= @writer.organization_id %>
</p>

<%= link_to 'Edit', edit_writer_path(@writer) %> |
<%= link_to 'Back', writers_path %>