config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :chief_editors
  resources :writers
  resources :users
  resources :organizations

  resources :sessions, only: [:new, :create, :destroy]

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  get ':id', to: 'home#index', constraints: { id: /\d+/ }

  get 'stories/new', to: 'stories#new'
  post 'stories/create', to: 'stories#create'
  
  get 'stories/:id/edit', to: 'stories#edit', constraints: { id: /\d+/ }
  post 'stories/:id/update', to: 'stories#update', constraints: { id: /\d+/ }
  post 'stories/:id/status', to: 'stories#status', constraints: { id: /\d+/ }
  post 'stories/:id/comment', to: 'stories#comment', constraints: { id: /\d+/ }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/chief_editor.rb
class ChiefEditor < User
  belongs_to :organization
  has_secure_password
end

app/controllers/chief_editors_controller.rb
class ChiefEditorsController < ApplicationController
  before_action :set_chief_editor, only: [:show, :edit, :update, :destroy]

  # GET /chief_editors
  # GET /chief_editors.json
  def index
    @chief_editors = ChiefEditor.all
  end

  # GET /chief_editors/1
  # GET /chief_editors/1.json
  def show
  end

  # GET /chief_editors/new
  def new
    @chief_editor = ChiefEditor.new
  end

  # GET /chief_editors/1/edit
  def edit
  end

  # POST /chief_editors
  # POST /chief_editors.json
  def create
    @chief_editor = ChiefEditor.new(chief_editor_params)

    respond_to do |format|
      if @chief_editor.save
        format.html { redirect_to @chief_editor, notice: 'Chief editor was successfully created.' }
        format.json { render :show, status: :created, location: @chief_editor }
      else
        format.html { render :new }
        format.json { render json: @chief_editor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chief_editors/1
  # PATCH/PUT /chief_editors/1.json
  def update
    respond_to do |format|
      if @chief_editor.update(chief_editor_params)
        format.html { redirect_to @chief_editor, notice: 'Chief editor was successfully updated.' }
        format.json { render :show, status: :ok, location: @chief_editor }
      else
        format.html { render :edit }
        format.json { render json: @chief_editor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chief_editors/1
  # DELETE /chief_editors/1.json
  def destroy
    @chief_editor.destroy
    respond_to do |format|
      format.html { redirect_to chief_editors_url, notice: 'Chief editor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chief_editor
      @chief_editor = ChiefEditor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chief_editor_params
      params.require(:chief_editor).permit(:name, :email, :password, :password_confirmation, :type, :organization_id)
    end
end

app/helpers/chief_editors_helper.rb
module ChiefEditorsHelper
end

app/views/chief_editors/_form.html.erb
<%= form_with(model: chief_editor, local: true) do |form| %>
  <% if chief_editor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chief_editor.errors.count, "error") %> prohibited this chief_editor from being saved:</h2>

      <ul>
        <% chief_editor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :organization_id %>
    <%= form.text_field :organization_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chief_editors/edit.html.erb
<h1>Editing Chief Editor</h1>

<%= render 'form', chief_editor: @chief_editor %>

<%= link_to 'Show', @chief_editor %> |
<%= link_to 'Back', chief_editors_path %>

app/views/chief_editors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chief Editors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Type</th>
      <th>Organization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chief_editors.each do |chief_editor| %>
      <tr>
        <td><%= chief_editor.name %></td>
        <td><%= chief_editor.email %></td>
        <td><%= chief_editor.type %></td>
        <td><%= chief_editor.organization_id %></td>
        <td><%= link_to 'Show', chief_editor %></td>
        <td><%= link_to 'Edit', edit_chief_editor_path(chief_editor) %></td>
        <td><%= link_to 'Destroy', chief_editor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chief Editor', new_chief_editor_path %>

app/views/chief_editors/new.html.erb
<h1>New Chief Editor</h1>

<%= render 'form', chief_editor: @chief_editor %>

<%= link_to 'Back', chief_editors_path %>

app/views/chief_editors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @chief_editor.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @chief_editor.email %>
</p>

<p>
  <strong>Type:</strong>
  <%= @chief_editor.type %>
</p>

<p>
  <strong>Organization:</strong>
  <%= @chief_editor.organization_id %>
</p>

<%= link_to 'Edit', edit_chief_editor_path(@chief_editor) %> |
<%= link_to 'Back', chief_editors_path %>